### ISSUE TITLE
support yarn workspaces

### ISSUE THREAD

**Issue by akurinnoy** [eclipse/theia-plugin-packager#3]
If we try to package plugin in yarn workspace we will have error:
```
irst-plugin: => 🚒 The dependency /Users/yevhen/work/test/test-plugin-packager/plugins/first-plugin/node_modules/aproba is referenced but is not available on the filesystem
first-plugin: error Command failed with exit code 1.
first-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
first-plugin: error Command failed with exit code 1.
first-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prepare exited 1 in 'first-plugin'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
To reproduce the problem clone and build: https://github.com/evidolob/test-plugin-packager

## Explanation

Currently, this tool isn't able to pack a plugin which is a part of a monorepository. 
I see here two problems at least:
- `yarn list` returns dependencies for all packages including packages (plugins) itself;
- package's dependencies are usually hoisted to the workspace root. 

## How to fix 

I believe, the first problem could be solved by filtering all the dependencies by a package (plugin) name which gives us only dependencies of a plugin.
For the second problem, we need to keep in mind that dependency could be resolved on the filesystem to `/node_modules` in the root of workpace or some `/plugins/plugin-name/node_modules` as well.

**Comment by benoitf** [comment]
I haven't seen this bug until now.
Should be straight-forward I had to handle something similar for theia generator

**Comment by benoitf** [comment]
should be fixed by https://github.com/eclipse/theia-plugin-packager/pull/5
